#!/usr/bin/env bash
# displays list of currently running processes.
# show all processes, for all users, including those
# which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

ps -auxf
